### ISSUE TITLE
[BUG] Case sensitive .css file

### ISSUE THREAD

**Issue by cwchong** [tractorcow/silverstripe-sliderfield#14]
In SliderField.php, the requirements line:

`Requirements::css('tractorcow/silverstripe-sliderfield:client/dist/styles/SliderField.css');`

needs to be updated to 

`Requirements::css('tractorcow/silverstripe-sliderfield:client/dist/styles/sliderfield.css');`

as the the .css is lowercased

**Comment by tractorcow** [comment]
Fixed in another PR. Happy birthday this ticket!
