### ISSUE TITLE
Uppercase in css Requirement

### ISSUE THREAD

**Issue by BW-Hosting** [tractorcow/silverstripe-sliderfield#18]
in SliderField.php Line 130:
`Requirements::css('tractorcow/silverstripe-sliderfield:client/dist/styles/SliderField.css');`
CSS Name is lowercase and it create errors

**Comment by tractorcow** [comment]
I fixed by making a new 4.0.1 release :) https://github.com/tractorcow/silverstripe-sliderfield/compare/4.0.0...4.0.1
