### ISSUE TITLE
Composer link string broken?!

### ISSUE THREAD

**Issue by mhenden** [tractorcow/silverstripe-sliderfield#2]
Doesn't do anything... I'm not sure why this isn't working?

**Comment by tractorcow** [comment]
Hi @mhenden , can you explain what you mean? Where is the composer link?

**Comment by mhenden** [comment]
Hi Damian

Not sure how to explain — screenshot attached of what Composer told me: 



Tried it with and without quotes and got same result. Hopefully it will make more sense to you than it does to me? 

cheers
MIKE

**Comment by tractorcow** [comment]
Sorry @mhenden the screenshot didn't come through.

I ran composer require and the module installed fine.

```
Damians-Spare-Macbook:ss31test dmooyman$ composer require "tractorcow/silverstripe-sliderfield" "3.0.*@dev"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Updating tractorcow/silverstripe-sliderfield (dev-master fe972c9 => 3.0.x-dev fe972c9)
    Checking out fe972c907d7db1f446f7246e21dd219dc4c8551c

Writing lock file
Generating autoload files

```

**Comment by tractorcow** [comment]
Try using composer selfupdate in case you are using an old version of composer. ;D

**Comment by mhenden** [comment]
That’s weird — I did update composer recently too. Wonder why it’s not working?

**Comment by mhenden** [comment]
Aha! 

Think it must be because I was pointed to the /Sites directory, not the actual WEBSITE directory!! 

Thanks for your help!

**Comment by tractorcow** [comment]
You're welcome. ;D
