### ISSUE TITLE
Class 'TractorCow\Sliderfield' not found

### ISSUE THREAD

**Issue by lx-s** [tractorcow/silverstripe-sliderfield#22]
Hi!

I installed `silverstripe-sliderfield` with composer on Silverstripe 4.5.2 and tried to create `SliderField`:

```php
...
use TractorCow\Sliderfield;
...
$strengthEnduranceSlider = new SliderField('StrengthEnduranceIndex', 'Stärke & Ausdauer', 0, 10);
```

Unfortunately, when opening the CMS Page I get the error: 
```
[Emergency] Uncaught Error: Class 'TractorCow\Sliderfield' not found
GET /admin/pages/edit/EditForm/9/field/Workouts/item/1/edit?gridState-Workouts-0={%22GridFieldSortableHeader%22%3A{%22SortColumn%22%3A[]}%2C%22GridFieldFilterHeader%22%3A{%22Columns%22%3Anull}%2C%22GridFieldPaginator%22%3A{%22currentPage%22%3A1%2C%22itemsPerPage%22%3A15}%2C%22GridFieldSortableRows%22%3A{%22sortableToggle%22%3Afalse}}
```

I'm really not sure what causes this, as all other modules work without a problem (fluent, gridfield-extensions, etc.).

Thanks for your time!

**Comment by tractorcow** [comment]
Did you mean `SliderField` not `Slidelfield`? Some filesystems are case sensitive.

**Comment by lx-s** [comment]
`use SliderField` or `use Sliderfield` makes unfortunately no difference.

**Comment by jellygnite** [comment]
I know this is a late reply but shouldn't it be:
`use TractorCow\SliderField\SliderField;`

**Comment by lx-s** [comment]
Ah yes - that's it. Thanks @jellygnite :)
