### ISSUE TITLE
Values above 999 truncated.

### ISSUE THREAD

**Issue by MattyBalaam** [tractorcow/silverstripe-sliderfield#9]
Perhaps this is a GB localised issue?

Values about 999 come in via this.val() in a format: 1,000.

parseInt() just takes the value  before the comma.

I'm on silverstripe 3.4.1.

Will submit a pull request

**Comment by tractorcow** [comment]
Fixed with https://github.com/tractorcow/silverstripe-sliderfield/pull/10
